//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datafirst.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class gamer
    {
        public int gamer_id { get; set; }
        public string gamer_name { get; set; }
        public string game_type { get; set; }
        public Nullable<int> salary { get; set; }
    }
}
